OBJ     =       VecTileDriver.obj VecTileDatasource.obj VecTileLayer.obj VecTileUtils.obj VecTileResultLayer.obj
EXTRAFLAGS =	-I.. -I..\..

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)

clean:
	-del *.obj *.pdb
